name: Renew

on:
  schedule:
    - cron: "35 6 * * 2,4,6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Depends
        run: |
          python -m pip install --upgrade requests
          python -m pip install --upgrade beautifulsoup4
      - name: Renew
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python euserv.py
